### ISSUE TITLE
Not found error when compiling

### ISSUE THREAD

**Issue by lyingju** [felixlucien/flutter-autocomplete-textfield#1]
Error: Type 'TextInputAction' not found.

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel beta, v0.5.1, on Mac OS X 10.13.4 17E199, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK 28.0.1)
[✓] iOS toolchain - develop for iOS devices (Xcode 9.4.1)
[✓] Android Studio (version 3.1)
[✓] Connected devices (1 available)

**Comment by felixmccuaig** [comment]
Hey, thanks for raising this issue; it seems that the TextInputAction parameter has been removed or something.
