### ISSUE TITLE
Not Showing items overlay in my view hierarchy but it manages to..

### ISSUE THREAD

**Issue by john-ravi** [felixlucien/flutter-autocomplete-textfield#10]
Not Showing items overlay in my view hierarchy but it manages to execute itemFilter and itemBuilder with desired results. Is there something in this layout below stopping to show results.

Parents from top Scaffold -> Stack -> Container -> Card ->ListView:

First LAyout: 
```
Container(
 child: textFieldCities,
),

```
But showing the result using this layout with height set on containing Container
```
 Container(
    height: 300.0,
    child: textFieldStates,
  ),
```

But this is ugly and not desired to manually put height and the resulting overlay glides through all this 300. height

**Comment by john-ravi** [comment]
```
Column(
 children: <Widget>[
  Expanded(child: Card(
     child: ListView())),
              ],
)
```

This WORKED!

**Comment by john-ravi** [comment]
But suggestions overlay is only visible after closing the keyboard!!

**Comment by felixmccuaig** [comment]
Seems like a complex problem, I'll take a look at it soon. If you manage to solve it feel free to pull request. :D

**Comment by felixmccuaig** [comment]
It seems to me that the layout is resizing for the keyboard. The scaffold has a parameter called resizeToAvoidBottomPadding. This is true by default, however, disabling it solves your problem.
