### ISSUE TITLE
Is there a way to use Stream suggestions from firebase?

### ISSUE THREAD

**Issue by Karlheinzniebuhr** [felixlucien/flutter-autocomplete-textfield#107]
I'd like to consume a stream of suggestions from firebase. But I haven't found a way to do this with AutoCompleteTextField.

**Comment by Molkars** [comment]
You'd need to call the `updateSuggestions` method from AutoCompleteTextFieldState in your listen callback for the stream.

**Comment by Karlheinzniebuhr** [comment]
That worked, thanks!
