### ISSUE TITLE
How do I change actual text field text value?

### ISSUE THREAD

**Issue by UG** [felixlucien/flutter-autocomplete-textfield#11]
in usual TextFeild using controller.text to modify TextField's text value.
This widget don't have Textfield controller How can I modify text in TextField.

for delete text , using clear() understand, what if I want "location:New  York" for search text bar.

**Comment by infl3x** [comment]
I agree, I would like to see maybe the `TextField` itself exposed for more flexibility.

**Comment by felixmccuaig** [comment]
Just published 1.6.1, textField is now exposed.
