### ISSUE TITLE
Suggestion's Position

### ISSUE THREAD

**Issue by tomcajot** [felixlucien/flutter-autocomplete-textfield#112]
It'd be great if we could choose whether the suggestions appear above / under the textfield. On small phones when the keyboard comes up it is kinda difficult to see the suggestions.

**Comment by WaterHashira** [comment]
hey @tomcajot , I would like work on it

**Comment by tomcajot** [comment]
> hey @tomcajot , I would like work on it

I don't really get what you mean?

**Comment by felixmccuaig** [comment]
@tomcajot The issue here is when rendering the suggestions we render downwards, if we render them above the textfield we have to reverse the rendering direction from bottom to top. Is this the functionality you had in mind?

**Comment by felixmccuaig** [comment]
#86
