### ISSUE TITLE
how do i make thr text filtering non case sesitivite but the value remains the same in the suggestions i.e retains its case

### ISSUE THREAD

**Issue by sanidhya711** [felixlucien/flutter-autocomplete-textfield#113]
i saw soemthing like this on the bottom of the basic usage 
itemFilter: (item, query) { return item.toLowerCase().startsWith(query.toLowerCase()); }
but i cant understand where to put this since the Widget dosent have any itemFilter property that we can set

**Comment by taimoor522** [comment]
you should look again because widget has itemFilter property.
