### ISSUE TITLE
Supports Null safety

### ISSUE THREAD

**Issue by RaineCode178** [felixlucien/flutter-autocomplete-textfield#114]
When will this package supports null safety

**Comment by sfabio01** [comment]
@RaineCode178 I migrated the project to null safety and made a pull request but seems the project is no longer supported, the last merge was in October 2019 :(

**Comment by tolotrasamuel** [comment]
Until the author revive this projects or delegates its maintenance, please let's all support the forked version that supports null safety and give it a like https://pub.dev/packages/autocomplete_textfield_ns

**Comment by felixmccuaig** [comment]
Just added null safety in version 2.0.0 :)
