### ISSUE TITLE
Display selected item in autocomplete textfield

### ISSUE THREAD

**Issue by DK15** [felixlucien/flutter-autocomplete-textfield#14]
I want to show the selected / clicked item from suggestion list in textfield. How do I do that ? I know textfield is now exposed in latest version, but I don’t know how to use controller with autocomplete textfield. Please see my detailed question here : 

https://stackoverflow.com/questions/53590156/how-to-set-value-in-autocompletetextfield

**Comment by felixmccuaig** [comment]
Off the top my head, you would use textfield.controller.text = “YOUR TEXT HERE"

**Comment by felixmccuaig** [comment]
So as in

itemSubmitted: (item) {
	setState(() => autocompletetextfield.textfield.controller.text = item. autocompleteterm);
}

**Comment by DK15** [comment]
Thanks, I will try that now.

**Comment by DK15** [comment]
That worked. I also had to set `clearOnSubmit: false` to be able to show the value in textfield.
