### ISSUE TITLE
Keyboard hide suggestions list.

### ISSUE THREAD

**Issue by zinwalin** [felixlucien/flutter-autocomplete-textfield#15]
it's better to use ListView for suggestions instead of Card widget.

**Comment by felixmccuaig** [comment]
You're going to have to give a better description of the problem. Perhaps a reason why listview is better and the issue the change would aim to solve.

**Comment by benmeemo** [comment]
I encountered this as well. The problem I saw is that when autocomplete was the last widget in a column and the keyboard opened, the keyboard hid the suggestions and it was impossible to scroll down to see the suggestions.

**Comment by paulosilva159** [comment]
I did something to avoid this. I put the suggestions list on top of the Autocomplete field. 

I changed the height of the suggestions list to 120. With both CompositedTransformTarget and CmopositedTransformFollower, the suggestion list and the TextFormField are aligned on the topLeft, to i just had to calculate how to align the list on top based on both heights (TextFormField ~= 150) and on the screen height.

It's just a quick workaround. I don't want this to be my final answer to this, but for now, it works

```
CompositedTransformTarget(
        link: _link,
        child: Autocomplete<T>(
          optionsViewBuilder: (context, onSelected, options) =>
              CompositedTransformFollower(
            // Changed here
            followerAnchor: Alignment(
              -1,
              -1 + (120 + 150) / (MediaQuery.of(context).size.height),
            ),
            link: _link,
            child: Align(
              alignment: Alignment.topLeft,
              child: Material(
                elevation: 4.0,
                child: SizedBox(
                // Changed here
                  height: 120.0,
                  child: ListView.builder(
                    padding: EdgeInsets.zero,
                    itemCount: options.length,
                    itemBuilder: (BuildContext context, int index) {
                      final T option = options.elementAt(index);
                      return InkWell(
                        onTap: () {
                          onSelected(option);
                        },
                        child: Padding(
                          padding: const EdgeInsets.all(16.0),
                          child: Text(
                            displayStringForOption(option),
                          ),
                        ),
                      );
                    },
                  ),
                ),
              ),
            ),
          ),
         ...
      )
```
