### ISSUE TITLE
prefill

### ISSUE THREAD

**Issue by jamu1989** [felixlucien/flutter-autocomplete-textfield#16]
Hello, 
i love the autocomplete textfield. 

But is it possible to prefill it with a text?

Greetings from Germany

**Comment by felixmccuaig** [comment]
Hey,
I assume you mean what Flutter calls a "hintText" as in when the grey text inside the textfield that might say "example@email.com" and when you start typing it goes away. Or do you mean to actually set the value of the textField in advance?
Thanks, Felix.
Greetings from Australia :)

**Comment by Verbruik** [comment]
Hi Felixlucien,

Actually both solutions could be a nice to have :)

In my case I need a hint AND a prefill value when the widget is initialized, is this any planified improvement ?

And btw, manage the TextEditingController instead of hardcoding it in the sub TextField of the AutoCompleteTextFieldState could be nice :D

Anyway, the lib is pretty useful, good job :)

Greetings from Belgium ;)

**Comment by Theunodb** [comment]
Hi Felixlucien, 

I agree that both solutions will be useful. I'm using your package to select a value from a list when creating an object with a couple of text fields, but i need to set the initial value for the textfield when i edit the object.

In my case i'm using Input decoration with labeltext, which hides the hint text (hides it until you select the value)

Would be great to have a controller available, if not, a field where we can set the initial value.

**Comment by Verbruik** [comment]
Hi Theunodb,

Actually you can work arround those missing features, but it still not the best solution.

In my case I use the GlobalKey and retreive the currentState of the controller with it. With this you can init the value of the textField when the state is initialized and the hintText still visible even when the focus isn't on the text field.

```dart 
final GlobalKey<AutoCompleteTextFieldState<MyModel>> _globalKey= GlobalKey();

@override
  void initState() {

      WidgetsBinding.instance.addPostFrameCallback((_) =>
      _globalKey.currentState.textField.controller.text = 'Init value'
      );

    super.initState();
  }```

**Comment by Theunodb** [comment]
Is this something thats on your roadmap? Would be great to have this, even though @Verbruik workaround exists, it would be great to have a more elegant solution.
