### ISSUE TITLE
Question :  How do we populate a changing suggestions list via a Future DB call? 

### ISSUE THREAD

**Issue by sjmcdowall** [felixlucien/flutter-autocomplete-textfield#17]
I was just wondering if maybe you or someone has an example of a more complex situation like I want to implement .  Well, did implement using a different Widget -- but want to convert to this one.  Basically we have a TextField suggestion box -- but we want to debounce the text to 300 ms and take the result to query a DB to fill in the suggestions .. 

Maybe with update suggestions (now added) this is pretty feasible? Just wondering best practices ..

**Comment by felixmccuaig** [comment]
Yeah sounds feasible to me, to do so I would use a pattern like [this](https://medium.com/@griffinmichl/implementing-debounce-in-javascript-eab51a12311e), it doesn't look too challenging.
