### ISSUE TITLE
Debounce textChanged

### ISSUE THREAD

**Issue by hbdejesus** [felixlucien/flutter-autocomplete-textfield#18]
Is there a way to debounce the textChange in order to not flood the server with API calls every time you input a text?

**Comment by felixmccuaig** [comment]
None implemented at the moment. Off the top of my head, to implement it, I would use a pattern like [this](https://medium.com/@griffinmichl/implementing-debounce-in-javascript-eab51a12311e)

**Comment by hbdejesus** [comment]
I'll try this out. Thanks!
