### ISSUE TITLE
The suggestions appear in Overlay which is covered by software keyboard

### ISSUE THREAD

**Issue by spidgorny** [felixlucien/flutter-autocomplete-textfield#22]
![image](https://user-images.githubusercontent.com/1579235/53126716-14e28480-3561-11e9-901f-5a1704cf6ce4.png)

See the screenshot above. Notice the blue line just above the keyboard? This is the suggestion popup. The position is calculated incorrectly when software keyboard is open. Hiding the keyboard allows me to see the suggestion, but 99% of the people will not notice.
I suggest to (a) detect the height of the software keyboard and adjust the position accordingly. Or (b) attach the position to the text field. The suggestions should scroll WITH the page. Currently suggestions float ABOVE the page.
What do you think?

**Comment by felixmccuaig** [comment]
Should be fixed by #31.
