### ISSUE TITLE
How to change text field color.

### ISSUE THREAD

**Issue by fazil-augr** [felixlucien/flutter-autocomplete-textfield#23]
I want to change the text field color. I tried so methods. No one working

    searchTextField = AutoCompleteTextField<Keyword>(
        style: new TextStyle(color: Colors.black, fontSize: 18.0),
                           decoration:  new InputDecoration(
                             border: InputBorder.none,
                             fillColor: Colors.red,
              )
   )

Is there any solution?

**Comment by hbdejesus** [comment]
You what you mean by color is the fillColor, you need to set the "filled" property of InputDecoration to true.

Ex.
`new TextStyle(color: Colors.black, fontSize: 18.0),
                       decoration:  new InputDecoration(
                         border: InputBorder.none,
                         filled: true,
                         fillColor: Colors.red,
          )`

Edit: 
Link to InputDecoration documentation [https://docs.flutter.io/flutter/material/InputDecoration-class.html](url)

**Comment by fazil-augr** [comment]
After re clean and rebuild it is working fine. I don't know why it is not working in previous. It is not working in hot reload also. Any way thanks my problem solved.

**Comment by fazil-augr** [comment]
After clean and rebuild it is working fine. I don't know why it is not working in previous. It is not working in hot reload also. Any way thanks my problem solved.
