### ISSUE TITLE
Suggestion list does not disappear after clicking

### ISSUE THREAD

**Issue by shtengel** [felixlucien/flutter-autocomplete-textfield#3]
After Suggestion list item had been clicked the list does not disappear.
please add  this line 

> listSuggestionsEntry.remove();

**Comment by felixmccuaig** [comment]
Hey, you're going to have to give me some more information on the issue in
order for me to fix it.

**Comment by shtengel** [comment]
Hey! When I type and the suggestion list appears and I click one of the items the keyboard and the suggestion list does not disappear

**Comment by felixmccuaig** [comment]
Sounds annoying. Are you using the latest plugin version? (1.4.1)

**Comment by felixmccuaig** [comment]
In the latest version (1.4.1) I have added two parameters for customization. submitOnSuggestionTap and clearOnSubmit. Enabling both should most likely fix your issue (they are enabled by default) as they will cause the plugin to submit (the TextField) when the user taps on a suggestion, therefore closing the keyboard and removing the suggestion list. clearOnSubmit can be used to automatically clear the TextField when a user submits.

**Comment by shtengel** [comment]
Thanks!
