### ISSUE TITLE
Suggestions not showing dynamic list

### ISSUE THREAD

**Issue by hbdejesus** [felixlucien/flutter-autocomplete-textfield#4]
Hi, is there a way to manually show the suggestions overlay?

I have this autocompletetextfield that gets it's suggestions from rest API. when I update the list of suggestions, the list is being updated but no suggestions are being shown. 

I'm fairly new to Flutter and TYIA for the help

**Comment by felixmccuaig** [comment]
Hey, this is a feature I will add soon. Sit tight!

**Comment by felixmccuaig** [comment]
Just added the requested feature! Does what it says on the tin. Use `addSuggestion`, `removeSuggestion` or `updateSuggestions` to change suggestions dynamically.

**Comment by sovoereign** [comment]
You

> Just added the requested feature! Does what it says on the tin. Use `addSuggestion`, `removeSuggestion` or `updateSuggestions` to change suggestions dynamically.

have you added this functionality?
