### ISSUE TITLE
itemSubmitted not working on Web

### ISSUE THREAD

**Issue by DeepakKanyanRor** [felixlucien/flutter-autocomplete-textfield#69]
All things working fine but **itemSubmitted** not calling when click on item . I running app on web. chrome

**Comment by bytejutsu** [comment]
same case with flutter apps for desktop

**Comment by halaylanderson** [comment]
same issue here...
tried everything but nothing seems to work

**Comment by AminYaghouti** [comment]
I have same issue for web.

**Comment by eduardothiesen** [comment]
Any news on this issue?

**Comment by AminYaghouti** [comment]
Nothing

Carlos Eduardo Gomes Thiesen <notifications@github.com> schrieb am Fr., 10.
Apr. 2020, 16:32:

**Comment by Donwaztok** [comment]
I've got a workaround.

the problem is in the "itemBuilder"

```
Consumer<UsuarioBloc>(
                builder: (BuildContext context, UsuarioBloc bloc) {
              return Container(
                margin: EdgeInsets.symmetric(vertical: 5, horizontal: 20),
                child: AutoCompleteTextField<OrganizacaoModel>(
                  controller: bloc.txtOrganizacao,
                  decoration: InputDecoration(
                    labelText: "Organização",
                    labelStyle: TextStyle(
                      color: Colors.grey[600],
                      fontWeight: FontWeight.bold,
                      fontSize: 15,
                    ),
                    border: OutlineInputBorder(
                      borderRadius: BorderRadius.all(Radius.circular(10.0)),
                      borderSide: BorderSide(width: 0, color: Colors.grey),
                    ),
                    fillColor: ColorUtil.white,
                    filled: true,
                    suffixIcon: new Icon(Icons.search),
                  ),
                  itemSubmitted: (item) =>
                      setState(() => bloc.selectedOrg = item),
                  key: bloc.orgKey,
                  suggestions: orgBloc.organizacoes,
                  itemBuilder: (context, suggestion) {
                    return Listener(
                      child: ListTile(
                        leading: Icon(Icons.info),
                        title: Text(suggestion.nome),
                      ),
                      onPointerDown: (item) {
                        bloc.txtOrganizacao.text = suggestion.nome;
                        bloc.selectedOrg = suggestion;
                      },
                    );
                  },
                  itemSorter: (a, b) => a.nome.compareTo(b.nome),
                  itemFilter: (suggestion, input) => suggestion.nome
                      .toLowerCase()
                      .startsWith(input.toLowerCase()),
                ),
              );
            }),
```

**Comment by shivaniaakanksha** [comment]
> I've got a workaround.
> 
> the problem is in the "itemBuilder"
> 
> ```
> AutoCompleteTextField<Model>(
>                   controller: bloc.txt,
>                   decoration: InputDecoration(
>                     labelText: "Organização",
>                     labelStyle: TextStyle(
>                       color: Colors.grey[600],
>                       fontWeight: FontWeight.bold,
>                       fontSize: 15,
>                     ),
>                     border: OutlineInputBorder(
>                       borderRadius: BorderRadius.all(Radius.circular(10.0)),
>                       borderSide: BorderSide(width: 0, color: Colors.grey),
>                     ),
>                     fillColor: ColorUtil.white,
>                     filled: true,
>                     suffixIcon: new Icon(Icons.search),
>                   ),
>                   itemSubmitted: (item) =>
>                       setState(() => bloc.selected = item),
>                   key: bloc.orgKey,
>                   suggestions: orgBloc.organizacoes,
>                   itemBuilder: (context, suggestion) {
>                     return Listener(
>                       child: ListTile(
>                         leading: Icon(Icons.info),
>                         title: Text(suggestion.name),
>                       ),
>                       onPointerDown: (item) {
>                         bloc.txt.text = suggestion.name;
>                         bloc.selected = suggestion;
>                       },
>                     );
>                   },
>                   itemSorter: (a, b) => a.name.compareTo(b.name),
>                   itemFilter: (suggestion, input) => suggestion.name
>                       .toLowerCase()
>                       .startsWith(input.toLowerCase()),
>                 )
> ```

@Donwaztok Can you please elaborate on how you solved this problem?

**Comment by Donwaztok** [comment]
@shivaniaakanksha i've updated my post to show my code using the BlocPattern.
I've create a Consumer to this widget.

In the ItemBuilder, i've create a Listener with my items in the "Suggestions" list.
The listener will change de value of "SelectedOrg" (instance of OrganizacaoModel) and then the the AutoCompleteTextField will show the right value and i can use the "SelectedOrg" as my value in this widget.

Sorry for my english

**Comment by felixmccuaig** [comment]
taking a look

**Comment by felixmccuaig** [comment]
Hi all, I haven't had this issue when using the latest version (2.0.0)

Please let me know if it still exists.

**Comment by newtangled** [comment]
I am seeing this issue still using v2.0.1 - works fine for mobile but not for web

**Comment by wurayan** [comment]
I'm having this issue on v2.0.1. Tapping an item closes the list as expected, but itemSubmitted only gets called once in a lot of tries (so, it suddenly works once and stops working next).

Tested on a physical device and emulator, both have the same behavior.

Funny thing is it was working fine until yesterday, and I didn't touch on anything related to this part of my code in a few weeks, maybe it's something related to other packages?

**Comment by wurayan** [comment]
Coming back to update.
I've tried @Donwaztok solution and it worked for the last two months, but it stopped working today, this time the itemBuilder is not being called at all.
Also, like the last time, I didn't touch in anything related to this part of the code, it just stopped working by itself.
