### ISSUE TITLE
Hi how to use custom object 

### ISSUE THREAD

**Issue by sathishRA91** [felixlucien/flutter-autocomplete-textfield#8]
I am using custom object but it return instance of object string only in textsubmit

**Comment by suparnavg** [comment]
@sathishRA91 did you manage to figure this out?

**Comment by sathishRA91** [comment]
@suparnavg yes creating two list one for ID and another for String. match the index position to retrieve specific ID that's the way i find out temporary solution.

**Comment by suparnavg** [comment]
Good hack, thanks!

**Comment by felixmccuaig** [comment]
Good pickup, I'll take a look into returning the selected object. :D

**Comment by felixmccuaig** [comment]
I just added the fix! It's live on pub version 1.6.0

**Comment by sathishRA91** [comment]
@felixlucien great thanks
