### ISSUE TITLE
Suggestions Pop up direction [feature request]

### ISSUE THREAD

**Issue by praharshbhatt** [felixlucien/flutter-autocomplete-textfield#86]
Currently have the textFormfield at the bottom of the screen. So, all the suggestions appear behind the keyboard.
Requesting a way to set the direction of the pop ups- either above or below the Textformfield.

![Screenshot_1593702675](https://user-images.githubusercontent.com/30700808/86376365-84639a80-bca4-11ea-88aa-f8486d5a1500.png)
![Screenshot_1593702676](https://user-images.githubusercontent.com/30700808/86376369-862d5e00-bca4-11ea-87e6-0ad0bf997ac9.png)

**Comment by qcuong97** [comment]
me, too 🤣  but u instead of https://pub.dev/packages/flutter_typeahead#-readme-tab-

**Comment by felixmccuaig** [comment]
Ill take a look

**Comment by felixmccuaig** [comment]
Added, however, it still has not been rigorously tested... it's in development branch. You can access it by downloading this repository and checking out development branch. I encourage you to test the changes using `suggestionsDirection` and `suggestionWidgetHeight`.

**Comment by Karlheinzniebuhr** [comment]
Is the updated version going to pub.dev anytime soon  ? The latest version is from Jul 2, 2019

**Comment by vmkgalvatron** [comment]
I also want to use this this feature. Please put it in production.
@felixlucien @khamasaki @msalinas1088

**Comment by vmkgalvatron** [comment]
How to use flutter type ahead to show suggestions from bottom? @qcuong97 

> me, too 🤣 but u instead of https://pub.dev/packages/flutter_typeahead#-readme-tab-

**Comment by felixmccuaig** [comment]
Should be included in 2.0.0 :)
