### ISSUE TITLE
How to stay focused in Textfield when submitted?

### ISSUE THREAD

**Issue by adschi** [felixlucien/flutter-autocomplete-textfield#94]
Hey I´m using this Textfield for adding items to a List. I want to stay focused when submitting an item, but currently every time I tap an item the keyboard dismisses.
Could anybody tell me how to do this? Thanks in advance.

**Comment by BallisticSwami** [comment]
I'm having the same problem. Keyboard loses focus as soon as you tap on it.

**Comment by felixmccuaig** [comment]
Use custom FocusNode
